INSERT INTO tasks (`created_at`, `title`, `description`, `author_id`, `category_id`, `city_id`, `status_id`, `address`, `finance`)
VALUES
  (NOW() - interval 9 day, 
  'Qui veniam aut dolorem dolores.', 
  'Voluptatum saepe officiis repellendus laboriosam. Et excepturi numquam aut tempora vero. Et aperiam ad est necessitatibus autem. Maiores in unde et cumque impedit. Omnis maxime sit molestiae qui. Beatae eveniet aut ea maxime reprehenderit non.', 
  9, 
  6, 
  697, 
  1,
  'Белгород, улица Пушкина',
  1550),
  (NOW() - interval 8 day,
  'Sed error quam recusandae ut sapiente.',
  'Dolor voluptatum sed illo. Eos eum cupiditate quo eius. Aperiam consequatur et repellendus quos. Omnis aut ut dignissimos quisquam. Exercitationem numquam officiis aut. Voluptas maiores voluptatem rerum ducimus neque ipsum ex.',
  7, 
  5, 
  954, 
  1,
  'Мытищи, улица Мира',
  2055),
  (NOW() - interval 7 day,
  'Et asperiores dolores beatae excepturi cum velit.',
  'Optio natus nostrum quasi officia amet doloribus dolor. Fuga eaque hic cumque voluptatem qui. A voluptatem consectetur provident itaque et. Pariatur quia harum ratione quia optio rem.',
  2,
  7,
  497,
  1, 
  'Клинцы, улица Герцина',
  1000),
  (NOW() - interval 6 day,
  'Et repudiandae voluptas quidem debitis.',
  'Nihil quidem rerum iste iure perspiciatis ipsum dolor quaerat. Non hic asperiores harum aliquid voluptatem. Qui nobis et et ut optio.',
  5,
  6,
  981,
  1, 
  'Казань, улица Свердлова',
  5000),
  (NOW() - interval 5 day,
  'Nihil error qui blanditiis aperiam.',
  'Enim molestiae ad corporis in veritatis tempore sed. Voluptatem iure odit molestiae non in. Illum cumque sit autem quis quisquam ducimus voluptas. Vero quam qui non explicabo velit saepe ut.',
  6,
  3,
  962,
  1,
  'Брянск, проспект Ленина',
  3000),
  (NOW() - interval 4 day,
  'Sit porro sit ipsum rerum.',
  'Enim ea saepe minus laboriosam et sed eum. Sit qui blanditiis et ducimus corporis vel sit. Adipisci laborum molestiae provident iusto. Provident repellendus voluptatibus nemo perspiciatis et quo odit. Nihil id saepe autem illo vitae sapiente eos. Facilis harum dolor eveniet amet fugiat totam.',
  7,
  5,
  802,
  1, 
  'Санкт-Петербург, Литейный проспект',
  2500),
  (NOW() - interval 3 day,
  'Ut expedita numquam molestias commodi qui laboriosam dolorem.',
  'Ducimus ipsa illo facere voluptatem accusamus. Eum qui enim quo sint. Eum possimus neque eius doloribus quasi aut. Occaecati dolorem dignissimos perferendis dolor. Fugit impedit harum corporis ex repellat neque et.',
  1,
  1,
  235,
  1,
  'Санкт-Петербург, набережная Фонтанки',
  10000),
  (NOW() - interval 2 day,
  'Aliquid est cupiditate esse provident in.',
  'Voluptatem voluptates cupiditate incidunt quia. Ducimus incidunt accusantium qui officia nesciunt omnis officia in. Nemo occaecati dolorum cum nostrum. Et aut magnam est unde est quis.',
  3,
  8,
  517,
  1,
  'Санкт-Петербург, Центральный район',
  3500),
  (NOW() - interval 1 day,
  'Sequi quaerat id voluptatem doloribus.',
  'Itaque neque id nostrum est ea et ut. Qui facilis cum quo accusamus qui. Esse quasi nihil aut nesciunt iusto voluptas molestiae ea. Fuga enim enim atque tempore.',
  9,
  3,
  995,
  1, 
  'Москва, улица Беловежская',
  2750),
  (NOW(),
  'Sunt sit error totam.',
  'Necessitatibus officia eos molestiae laudantium ducimus exercitationem omnis debitis. Corrupti nobis quas recusandae enim non cupiditate. Qui ad consequuntur repellat qui quis. Quia asperiores amet rerum laboriosam et delectus necessitatibus.',
  4,
  1,
  188,
  1, 
  'Пушкино, улица Просвещения',
  4800);